global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'api-backend'
    static_configs:
      - targets: ['localhost:4000']
    metrics_path: '/metrics'
    basic_auth:
      username: 'prometheus'
      password: 'password'
    scrape_interval: 5s