apiVersion: v1
kind: Service
metadata:
  name: api-backend-service
  labels:
    app: api-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http-alt
  selector:
    app: api-backend